version: "3"

services:
  frontend:
    image: gearmobile/timeapp-frontend-dev
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api

  api:
    image: gearmobile/timeapp-api-dev
    restart: always
    ports:
      - 5555:5000
    environment:
      PORT: 5000
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: time_db
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: time_db
    volumes:
      - db_data_pub:/var/lib/mysql

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080
    depends_on:
      - db

volumes:
  db_data_pub:
