# railway.toml

[services]

  [services.api]
  # Nom du service : "api"
  image = "imadch/cicd:api-latest"
  internal_port = 5000

  # Variables d'environnement (si nécessaire)
  [services.api.envs]
  PORT = "5000"
  MYSQL_HOST = "..."
  MYSQL_PORT = "3306"
  MYSQL_USER = "root"
  MYSQL_PASSWORD = "root"
  MYSQL_DATABASE = "time_db"
