# railway.toml

[services]
  [services.api]
  # On déploie directement l'image Docker (plus de détection auto)
  image = "imadch/cicd:api-latest"
  internal_port = 5000

  [services.api.envs]
  PORT = "5000"
  MYSQL_HOST = "db"
  MYSQL_USER = "root"
  MYSQL_PASSWORD = "root"
  MYSQL_DATABASE = "time_db"