[deploy]
startCommand = ""
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "api"
image = "imadch/cicdpart1:api-latest"
internal_port = 5000

[services.envs]
PORT = "5000"
MYSQL_HOST = "mysql-339b51b0.railway.internal" 
MYSQL_USER = "root"
MYSQL_PASSWORD = "iZryzEnACIfutJpNXWSgSrGbwqtCNHAe"
MYSQL_DATABASE = "railway"
MYSQL_PORT = "3306"

