name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and test frontend
    - name: Build frontend
      run: docker-compose build frontend

    - name: Test frontend
      run: |
        docker-compose run --rm frontend npm test || true

    # Build and test API
    - name: Build API
      run: docker-compose build api

    - name: Test API
      run: |
        docker-compose run --rm api npm test || true

    # Push to DockerHub if on main/master branch
    - name: Tag and push images to DockerHub
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        # Tag avec le hash du commit et latest
        docker tag frontend imadch/cicd:frontend-${{ github.sha }}
        docker tag frontend imadch/cicd:frontend-latest
        
        docker tag api imadch/cicd:api-${{ github.sha }}
        docker tag api imadch/cicd:api-latest
        
        # Push des images
        docker push imadch/cicd:frontend-${{ github.sha }}
        docker push imadch/cicd:frontend-latest
        docker push imadch/cicd:api-${{ github.sha }}
        docker push imadch/cicd:api-latest

  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

   
