name: CI/CD Pipeline

on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Frontend
      run: |
        docker build -t imadch/cicd:frontend-$GITHUB_SHA -t imadch/cicd:frontend-latest ./frontend
        docker push imadch/cicd:frontend --all-tags

    - name: Build and Push API
      run: |
        docker build -t imadch/cicd:api-$GITHUB_SHA -t imadch/cicd:api-latest ./api
        docker push imadch/cicd:api --all-tags

    - name: Run Frontend Tests
      run: docker run --rm imadch/cicd:frontend-latest npm test

    - name: Run API Tests
      run: docker run --rm -e MYSQL_HOST=db -e MYSQL_USER=root -e MYSQL_PASSWORD=root imadch/cicd:api-latest npm test

