name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and test frontend
    - name: Build frontend
      run: docker-compose build frontend

    - name: Test frontend
      run: |
        docker-compose run --rm frontend npm test || true

    # Build and test API
    - name: Build API
      run: docker-compose build api

    - name: Test API
      run: |
        docker-compose run --rm api npm test || true

    # Push to DockerHub if on main/master branch
    - name: Tag and push frontend image
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        docker tag frontend ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
        docker tag frontend ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}

    - name: Tag and push API image
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        docker tag api ${{ secrets.DOCKERHUB_USERNAME }}/api:latest
        docker tag api ${{ secrets.DOCKERHUB_USERNAME }}/api:${{ github.sha }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/api:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/api:${{ github.sha }}

  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
